[package]
name = "voxel-test"
version = "0.1.0"
authors = ["NathanFlurry <github@nathanflurry.com>"]
edition = "2018"

[dependencies]
noise = "0.5.1"
na = "0.16.6"  # TEMP:

glium = "0.23.0"
image = "0.21.0"
