[package]
name = "voxel-test"
version = "0.1.0"
authors = ["NathanFlurry <github@nathanflurry.com>"]
edition = "2018"

[dependencies]
winit = "0.18.1"
gfx-hal = "0.1.0"
gfx-backend-metal = "0.1.0"

noise = "0.5.1"

na = "0.16.6"  # TEMP:

[build-dependencies]
glsl-to-spirv = "0.1.7"
